import React from 'react';
import {AbsoluteFill,Audio,OffthreadVideo,Freeze,Sequence,staticFile,useCurrentFrame,interpolate} from 'remotion';
import {PRETENDARD} from './daesan-ending/approved/fonts';
import {WoodProfile} from './WoodProfile';
export const FRAMES=[151,171,243,180,243];
export const AUDIO=['scene01-v8.mp3','scene02-v2.mp3','scene03-v2.mp3','scene04-v2.mp3','scene05-v3.mp3'];
const green='#146335',ink='#18251f',muted='#647069',line='#ccd5cf',wash='#e3f0e5';
const ramp=(f:number,s:number,d=10)=>interpolate(f,[s,s+d],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp'});
const Card:React.FC<React.PropsWithChildren<{style?:React.CSSProperties}>>=({children,style})=><div style={{background:'white',border:`2px solid ${line}`,borderRadius:22,padding:36,boxSizing:'border-box',...style}}>{children}</div>;
// Approved 24 fps white-background motion, normal speed. Freeze at 3.933 s (frame 118 at composition 30 fps).
const Mascot=({open=false,start=0,x=84,y=1180}:{open?:boolean;start?:number;x?:number;y?:number})=>{const f=useCurrentFrame();if(f<start)return null;return <div style={{position:'absolute',left:x,top:y,width:355,height:470,overflow:'hidden'}}><Freeze frame={Math.min(f-start,118)}><OffthreadVideo muted src={staticFile(`assets/video/daesani-${open?'open-arms-explain':'point-right'}.mp4`)} style={{position:'absolute',width:490,height:871.111,left:-85,top:-222}}/></Freeze></div>};
const Head=({a,b}:{a:string;b:string})=><div style={{position:'absolute',left:84,right:84,top:270,fontSize:Math.max(a.length,b.length)>18?50:Math.max(a.length,b.length)>15?56:66,fontWeight:800,lineHeight:1.32,letterSpacing:-2}}>{a}<br/><span style={{color:green}}>{b}</span></div>;
const Note:React.FC<React.PropsWithChildren<{top?:number}>>=({children,top=1340})=><div style={{position:'absolute',left:485,top,width:510,fontSize:43,fontWeight:600,lineHeight:1.5}}>{children}</div>;
function Hook(){return <><Head a="목문틀 일체형 vs 분리형" b="어떤 차이가 있을까?"/><div style={{position:'absolute',left:84,right:84,top:580,display:'flex',gap:24}}>{['일체형','분리형'].map((t,i)=><Card key={t} style={{width:444,height:505,textAlign:'center',padding:'36px 20px'}}><div style={{fontSize:56,fontWeight:800,color:green}}>{t}</div><WoodProfile id={`hook-${i}`} split={i===1} gap={35} width={398} height={252}/><div style={{fontSize:33,color:muted}}>{i?'문틀 + 스토퍼 별도':'문틀과 스토퍼 한 몸'}</div></Card>)}</div><div style={{position:'absolute',left:84,top:1118,fontSize:25,color:muted}}>영림 단면 기반 단순화 · 내부 상세 생략</div><Mascot open/><Note>같은 목문틀도<br/><span style={{color:green}}>구성 방식이 달라요</span></Note></>}
function Structure(){const f=useCurrentFrame();const join=ramp(f,127,22);return <><Head a="분리형 = 문틀 + 스토퍼 별도" b="스토퍼를 따로 결합하는 구조"/><div style={{position:'absolute',left:84,top:580,fontSize:32,color:muted}}>두 부재의 구성과 결합 관계</div><Card style={{position:'absolute',left:425,top:690,width:571,height:650,padding:'35px 18px',borderColor:green}}><div style={{fontSize:43,fontWeight:800,color:f>=99?green:ink,textAlign:'center'}}>스토퍼</div><div style={{textAlign:'center',fontSize:36,color:green,opacity:1-join}}>↓</div><WoodProfile id="structure" split gap={48*(1-join)} width={531} height={335}/><div style={{textAlign:'center',fontSize:45,fontWeight:800,color:f>=77?green:ink}}>문틀</div><div style={{fontSize:29,color:muted,textAlign:'center',marginTop:26}}>별도 구성 → 결합</div></Card><Mascot x={60} y={990}/><div style={{position:'absolute',left:84,top:1500,fontSize:26,color:muted}}>영림 단면 기반 단순화 · 내부 상세 생략</div></>}
function Orders(){const f=useCurrentFrame();const late=f>=141;const width=interpolate(f,[141,177],[730,400],{extrapolateLeft:'clamp',extrapolateRight:'clamp'});return <><Head a="실제 발주는 분리형이 대부분" b={late?'하지만 바수가 작다면?':'많이 선택하는 분리형'}/><Card style={{position:'absolute',left:84,top:580,width:912,textAlign:'center',padding:'45px 36px',borderColor:green}}><div style={{fontSize:31,color:muted}}>영림 목문틀 · 실제 발주</div><div style={{fontSize:106,fontWeight:800,color:green,marginTop:18}}>분리형</div></Card><Card style={{position:'absolute',left:84,top:940,width:912,height:480,opacity:ramp(f,141)}}><div style={{fontSize:43,fontWeight:800}}>하지만 바수가 작다면?</div><div style={{height:90,width,background:wash,border:`2px solid ${green}`,borderRadius:8,margin:'58px auto 26px'}}/><div style={{textAlign:'center',fontSize:34,color:green}}>바수가 작아지면</div><div style={{textAlign:'center',fontSize:36,marginTop:40}}>선택 가능한 문틀 타입이 달라져요</div></Card></>}
function Criteria(){const f=useCurrentFrame();return <><Head a="분리형 최소 100바" b={f>=127?"가스켓은 110바부터":"가스켓 적용 기준 확인"}/><Card style={{position:'absolute',left:84,top:570,width:912,height:405,borderColor:green}}><div style={{display:'flex',alignItems:'baseline',gap:24}}><span style={{fontSize:136,fontWeight:800,color:green,lineHeight:1.15}}>100<span style={{fontSize:58}}>바</span></span><span style={{fontSize:40,fontWeight:800,opacity:ramp(f,57,7)}}>분리형 가능</span></div><div style={{marginTop:43,paddingTop:25,borderTop:`2px solid ${line}`,fontSize:49,fontWeight:800,opacity:ramp(f,82,7)}}>100바 → 가스켓 <span style={{color:ink}}>X</span></div></Card><Card style={{position:'absolute',left:84,top:1010,width:912,height:405,borderColor:green,opacity:ramp(f,127,8),background:wash}}><div style={{display:'flex',alignItems:'baseline',gap:24}}><span style={{fontSize:125,fontWeight:800,color:green,lineHeight:1.15}}>110<span style={{fontSize:53}}>바부터</span></span></div><div style={{fontSize:39,fontWeight:800,marginTop:18}}>분리형 가능</div><div style={{fontSize:49,fontWeight:800,color:green,marginTop:22}}>110바부터 → 가스켓 O</div></Card></>}
function Conclusion(){const f=useCurrentFrame();return <><Head a="100바 미만" b="일체형으로 발주"/><Card style={{position:'absolute',left:84,top:570,width:912,textAlign:'center',padding:'45px 36px'}}><div style={{fontSize:72,fontWeight:800}}>100바 미만</div><div style={{fontSize:54,color:green,margin:'8px 0'}}>↓</div><div style={{fontSize:83,fontWeight:800,color:green}}>일체형으로 발주</div></Card><div style={{position:'absolute',left:84,top:1040,fontSize:48,fontWeight:800,lineHeight:1.45}}>목문틀 발주 =<br/><span style={{color:green}}>바수 + 타입 함께 확인</span></div><Mascot start={128}/><div style={{position:'absolute',left:485,top:1240,width:510}}>{['바수','문틀 타입'].map((t,i)=><Card key={t} style={{fontSize:45,fontWeight:800,marginBottom:22,padding:28,borderColor:f>=[165,180][i]?green:line}}>{t}<span style={{float:'right',color:green,opacity:ramp(f,[165,180][i],6)}}>✓</span></Card>)}</div></>}
export const Scene=({id}:{id:number})=><AbsoluteFill style={{background:'#FFFFFF',color:ink,fontFamily:PRETENDARD}}><Audio src={staticFile(`assets/audio/${AUDIO[id-1]}`)}/><div style={{position:'absolute',left:84,right:84,top:150,fontSize:27,letterSpacing:2,color:green,fontWeight:600}}>대산 · 문틀 발주 가이드 <span style={{float:'right',color:muted}}>0{id} / 05</span></div><div style={{position:'absolute',left:84,right:84,top:211,height:2,background:line}}/>{React.createElement([Hook,Structure,Orders,Criteria,Conclusion][id-1])}<div style={{position:'absolute',left:84,bottom:165,fontSize:24,color:muted}}>DAESAN <span style={{marginLeft:18}}>건축자재 발주 정보</span></div></AbsoluteFill>;
export const Content=()=> <>{FRAMES.map((duration,i)=><Sequence key={i} from={FRAMES.slice(0,i).reduce((a,b)=>a+b,0)} durationInFrames={duration}><Scene id={i+1}/></Sequence>)}</>;
