import React from 'react';
import {AbsoluteFill,Audio,Composition,Img,interpolate,registerRoot,staticFile,useCurrentFrame,useVideoConfig} from 'remotion';
import {PRETENDARD} from './approved/fonts';
const INK='#20372e',PAPER='#f5f3ed';
const specs=[
{id:1,frames:125,audio:'scene01-tts-v5.mp3',lines:['히든도어도 일반 도어처럼','문만 설치하면 끝일까요?'],tag:'시공 전, 먼저 확인할 것',image:'hidden-door-scene01-hero-v1.png'},
{id:2,frames:178,audio:'scene02-tts-v4.mp3',lines:['문선 없이 벽과 문이 한 면처럼','이어지는 히든도어'],tag:'차이는 문 주변의 마감',image:''},
{id:3,frames:210,audio:'scene03-tts-v4.mp3',lines:['영림 히든도어 시공 조건','9mm 마감 벽체 필요'],tag:'목공 단계부터 준비',image:'hidden-door-scene03-carpentry-v1.png'},
{id:4,frames:220,audio:'scene04-tts-v8.mp3',lines:['9mm 합판·MDF로 벽체 마감','도어 설치 전 목공부터 준비'],tag:'문을 달기 전, 벽체 마감부터',image:'hidden-door-scene04-finish-v1.png'},
{id:5,frames:158,audio:'scene05-tts-v6.mp3',lines:['히든도어 완성도는','목공 단계부터 시작됩니다'],tag:'처음부터 함께 계획하세요',image:'hidden-door-scene01-hero-v1.png'}];
const Compare=()=>{const f=useCurrentFrame();return <div style={{position:'absolute',top:385,left:64,width:952}}><div style={{display:'flex',gap:24}}>{['normal','hidden'].map((kind,i)=><div key={kind} style={{width:464}}><div style={{fontSize:40,fontWeight:600,textAlign:'center',marginBottom:24}}>{i===0?'일반 도어':'히든도어'}</div><div style={{height:950,position:'relative',overflow:'hidden'}}><Img src={staticFile(`images/hidden-door-scene02-${kind}-v1.png`)} style={{width:'100%',height:'100%',objectFit:'cover'}}/>{i===0&&<svg width="464" height="950" style={{position:'absolute',inset:0}}><path d="M105 755V160H360V755" fill="none" stroke="#c8a25a" strokeWidth="5" strokeDasharray="1500" strokeDashoffset={interpolate(f,[8,42],[1500,0],{extrapolateLeft:'clamp',extrapolateRight:'clamp'})}/>}</div><div style={{fontSize:30,textAlign:'center',fontWeight:600,marginTop:28}}>{i===0?'문틀 주변에 문선':'벽과 문이 같은 면'}</div></div>)}</div></div>};
const Scene=({id}:{id:number})=>{const f=useCurrentFrame();const {durationInFrames}=useVideoConfig();const s=specs[id-1];return <AbsoluteFill style={{background:PAPER,color:INK,fontFamily:PRETENDARD}}>
{id!==2&&<><Img src={staticFile(`images/${s.image}`)} style={{position:'absolute',width:1080,height:1920,objectFit:'cover',transform:`scale(${interpolate(f,[0,durationInFrames],[1,1.012])})`}}/><AbsoluteFill style={{background:'linear-gradient(to bottom,rgba(245,243,237,0.92) 0%,rgba(245,243,237,0.66) 13%,transparent 23%,transparent 75%,rgba(245,243,237,0.95) 88%)'}}/></>}
<div style={{position:'absolute',top:125,left:76,right:100,fontSize:28,fontWeight:600,letterSpacing:2}}>DAESAN <span style={{fontWeight:500,letterSpacing:0,color:'#6e776f',marginLeft:22}}>히든도어 시공</span></div>
<div style={{position:'absolute',top:218,left:76,right:100,fontSize:40,fontWeight:600}}>{s.tag}</div>
{id===2&&<Compare/>}
{id===3&&<><svg style={{position:'absolute',inset:0}} width="1080" height="1920"><path d="M260 1500V335H770" fill="none" stroke="#dfbc72" strokeWidth="6" strokeDasharray="1750" strokeDashoffset={interpolate(f,[15,85],[1750,0],{extrapolateLeft:'clamp',extrapolateRight:'clamp'})}/></svg><div style={{position:'absolute',top:1360,left:76,padding:'14px 24px',background:'rgba(245,243,237,.94)',fontSize:66,fontWeight:800}}>9<span style={{fontSize:38}}>mm</span><span style={{fontSize:31,fontWeight:600,marginLeft:22}}>마감 벽체</span></div></>}
{id===4&&<div style={{position:'absolute',top:1350,left:76,right:100,background:'rgba(245,243,237,.94)',padding:'22px 26px',fontSize:37,fontWeight:600,borderLeft:'6px solid #bf9a55'}}>벽체 마감 <span style={{color:'#61766a',marginLeft:18}}>합판 · MDF</span></div>}
{id===5&&<div style={{position:'absolute',top:300,left:76,right:100,display:'flex',justifyContent:'space-between',fontSize:29,fontWeight:600}}>{['목공 준비','9mm 벽체 마감','완성'].map((t,i)=><React.Fragment key={t}>{i>0&&<span style={{color:'#859286'}}>→</span>}<span style={{opacity:interpolate(f,[i*13,i*13+10],[0.4,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp'})}}>{t}</span></React.Fragment>)}</div>}
<div style={{position:'absolute',left:76,right:100,top:1600,fontSize:id===2?48:52,fontWeight:800,lineHeight:1.38,letterSpacing:-1.8}}>{s.lines.map(t=><div key={t} style={{whiteSpace:'nowrap'}}>{t}</div>)}</div><div style={{position:'absolute',bottom:130,left:76,right:100,height:3,background:'#dddeda'}}><div style={{height:3,width:`${100*(f+1)/s.frames}%`,background:'#7b9484'}}/></div><Audio src={staticFile(`audio/${s.audio}`)} playbackRate={1}/>
</AbsoluteFill>};
registerRoot(()=> <>{specs.map(s=><Composition key={s.id} id={`HiddenDoorScene${s.id}`} component={Scene} defaultProps={{id:s.id}} width={1080} height={1920} fps={30} durationInFrames={s.frames}/>)}</>);
